- hosts: ubuntu_os
  become: yes
  gather_facts: yes
  gather_subset:
    - "!hardware"

  pre_tasks:
    - name: Enable Ubuntu Universe
      ansible.builtin.apt_repository:
        repo: "{{item}}"
      when: ansible_distribution == 'Ubuntu' and ansible_architecture == 'aarch64'
      with_items:
        - 'deb [arch=arm64] http://ports.ubuntu.com/ {{ansible_distribution_release}} main multiverse universe'
        - 'deb [arch=arm64] http://ports.ubuntu.com/ {{ansible_distribution_release}}-security main multiverse universe'
        - 'deb [arch=arm64] http://ports.ubuntu.com/ {{ansible_distribution_release}}-backports main multiverse universe'
        - 'deb [arch=arm64] http://ports.ubuntu.com/ {{ansible_distribution_release}}-updates main multiverse universe'
      register: multiverse_installed

    - name: Updated and Upgrade Packages
      ansible.builtin.apt:
        upgrade: full
        update_cache: yes
        state: latest
        autoclean: yes
      when: multiverse_installed.changed == "True"

